CREATE TABLE cards (
  cardid      TEXT UNIQUE               NOT NULL,
  dbfid       BIGINT UNIQUE PRIMARY KEY NOT NULL,
  name        TEXT                      NOT NULL,
  cardset     TEXT                      NOT NULL,
  faction     TEXT                      NOT NULL,
  rarity      TEXT                      NOT NULL,
  cost        INT                       NOT NULL,
  attack      INT                       NOT NULL,
  health      INT                       NOT NULL,
  armor       INT                       NOT NULL,
  text        TEXT                      NOT NULL,
  flavor      TEXT                      NOT NULL,
  entourage   TEXT []                   NOT NULL,
  collectible BOOLEAN                   NOT NULL,
  elite       TEXT                      NOT NULL,
  race        TEXT                      NOT NULL,
  playerclass TEXT                      NOT NULL,
  durability  INT                       NOT NULL
)